-- ============================================================
-- SNOWFLAKE: Create Database and Grant Permissions
-- ============================================================
-- 
-- Run this in Snowflake SQL Worksheet as ACCOUNTADMIN
-- 
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS GCMS_DEV;

-- Create schemas for all movements (layers) - MUST MATCH dbt_project.yml!
CREATE SCHEMA IF NOT EXISTS GCMS_DEV.MOVEMENT_I;    -- Raw data from Supabase
CREATE SCHEMA IF NOT EXISTS GCMS_DEV.MOVEMENT_II;   -- Bronze layer (dbt)
CREATE SCHEMA IF NOT EXISTS GCMS_DEV.MOVEMENT_III;  -- Silver layer (dbt)
CREATE SCHEMA IF NOT EXISTS GCMS_DEV.FINALE;        -- Gold layer (dbt)

-- Create a custom role for GCMS operations
CREATE ROLE IF NOT EXISTS GCMS_DEVELOPER;

-- Grant database-level permissions to role
GRANT USAGE ON DATABASE GCMS_DEV TO ROLE GCMS_DEVELOPER;

-- Grant permissions for MOVEMENT_I (Raw data)
GRANT USAGE ON SCHEMA GCMS_DEV.MOVEMENT_I TO ROLE GCMS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA GCMS_DEV.MOVEMENT_I TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GCMS_DEV.MOVEMENT_I TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GCMS_DEV.MOVEMENT_I TO ROLE GCMS_DEVELOPER;

-- Grant permissions for MOVEMENT_II (Bronze layer - dbt)
GRANT USAGE ON SCHEMA GCMS_DEV.MOVEMENT_II TO ROLE GCMS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA GCMS_DEV.MOVEMENT_II TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GCMS_DEV.MOVEMENT_II TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GCMS_DEV.MOVEMENT_II TO ROLE GCMS_DEVELOPER;

-- Grant permissions for MOVEMENT_III (Silver layer - dbt)
GRANT USAGE ON SCHEMA GCMS_DEV.MOVEMENT_III TO ROLE GCMS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA GCMS_DEV.MOVEMENT_III TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GCMS_DEV.MOVEMENT_III TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GCMS_DEV.MOVEMENT_III TO ROLE GCMS_DEVELOPER;

-- Grant permissions for FINALE (Gold layer - dbt)
GRANT USAGE ON SCHEMA GCMS_DEV.FINALE TO ROLE GCMS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA GCMS_DEV.FINALE TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GCMS_DEV.FINALE TO ROLE GCMS_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GCMS_DEV.FINALE TO ROLE GCMS_DEVELOPER;

-- Grant warehouse usage to role
GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE GCMS_DEVELOPER;

-- Grant the role to your user
GRANT ROLE GCMS_DEVELOPER TO USER ROBERTGONZALEZ;

-- Verify
SHOW DATABASES LIKE 'GCMS_DEV';
SHOW SCHEMAS IN DATABASE GCMS_DEV;

-- ============================================================
-- SUCCESS!
-- ============================================================
-- Database GCMS_DEV and schema MOVEMENT_I are ready
-- User ROBERTGONZALEZ has full permissions
-- Now retry the Airflow DAG
-- ============================================================
